name: Release Appimage

on:
  pull_request:
    types: [closed]
    branches: [ release-package ]

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 3.0.0
    - name: Create appimage
      run: |
        gem install bundler
        bundle install 
        bundle update
        rake appimage
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::$(cat lib/sheep_ast/version.rb | grep VERSION | cut -d "'" -f 2)
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get_version.outputs.VERSION  }}
        release_name: Release ${{ steps.get_version.outputs.VERSION }}
        draft: false
        prerelease: false
    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./out/run-sheep-ast-${{ steps.get_version.outputs.VERSION }}.glibc2.3-x86_64.AppImage
        asset_name: run-sheep-ast-${{ steps.get_version.outputs.VERSION }}.glibc2.3-x86_64.AppImage
        asset_content_type: application/zip
